services:
  - type: web
    name: dostify-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ENABLED
        value: true
  - type: web
    name: dostify-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://dostify-server.onrender.com
      - key: NEXT_PUBLIC_SERVER_URL
        value: https://dostify-server.onrender.com

